Improve backend implementation of the task module
ballerina-platform/module-ballerina-task pull request #31
Opened 2020-10-26 08:14 UTC by kalaiyarasiganeshalingam

## Purpose
$Subject

Fixes [#59](https://github.com/ballerina-platform/ballerina-standard-library/issues/59)

2020-10-27 05:32 UTC, BuddhiWathsala requested changes

2020-10-27 05:32 UTC, BuddhiWathsala commented on task-ballerina/src/task/listener.bal
>              if (noOfRecurrences == 1) {
Better to convert this to a `else if` clause. That will improve performance.

2020-11-05 07:45 UTC, ThisaruGuruge commented on task-native/src/main/java/org/ballerinalang/stdlib/task/actions/TaskActions.java
> +            return Utils.createTaskError("Cannot resume Listener/Scheduler." + e.getMessage());
```suggestion
            return Utils.createTaskError("Cannot resume the Listener/Scheduler. " + e.getMessage());
```

Check for the other places as well.

2020-11-05 07:45 UTC, ThisaruGuruge commented on task-native/src/main/java/org/ballerinalang/stdlib/task/actions/TaskActions.java
> +            return Utils.createTaskError("Cannot attach the service to the Listener/Scheduler." + e.getMessage());
```suggestion
            return Utils.createTaskError("Cannot attach the service to the Listener/Scheduler. " + e.getMessage());
```

These error messages seem inconsistent. Check for the other places as well.

2020-11-05 07:45 UTC, ThisaruGuruge commented on task-native/src/main/java/org/ballerinalang/stdlib/task/objects/TaskScheduler.java
> +    @SuppressWarnings("unchecked")
Why do we need this `SuppressWarning` here? If unnecessary, shall we remove it? Check for the other places as well.

2020-11-05 07:45 UTC, ThisaruGuruge commented on task-native/src/main/java/org/ballerinalang/stdlib/task/actions/TaskActions.java
> +                Object cronExpression = configurations.get(TaskConstants.MEMBER_CRON_EXPRESSION);
Shouldn't this be:

```suggestion
                BString cronExpression = configurations.getStringvalue(TaskConstants.MEMBER_CRON_EXPRESSION);
```

2020-11-05 07:45 UTC, ThisaruGuruge commented on task-native/src/main/java/org/ballerinalang/stdlib/task/utils/Utils.java
>          String cronExpression = record.toString();
```suggestion
    public static String validateCronExpression(BString expression) throws SchedulingException {
        String cronExpression = expression.getValue();
```

2020-11-05 07:45 UTC, ThisaruGuruge commented on task-native/src/main/java/org/ballerinalang/stdlib/task/utils/Utils.java
> +        if (configurations.getIntValue(TaskConstants.FIELD_NO_OF_RUNS) == null) {
This can't be null

2020-11-05 07:45 UTC, ThisaruGuruge commented
Just another question, did you check how these changes affect the other stdlib modules, such as Cache?

2020-11-05 11:52 UTC, kalaiyarasiganeshalingam commented on task-ballerina/src/task/commons.bal
> +    int noOfRecurrences = 0;
The default value is 0. It executes the job forever. I have added this in the [description](https://github.com/ballerina-platform/module-ballerina-task/pull/31/files/ff437c00c81d35975d3d2d37b91114ca2c7923c2#diff-50766c35f035a8c0ec53a3724fbe150acda7722730f46c6aa4b73e6aa9c2fb16R22).

2020-11-06 04:16 UTC, kalaiyarasiganeshalingam commented
> Just another question, did you check how these changes affect the other stdlib modules, such as Cache?

Yes, I have checked the Cache, it has worked.

2020-11-06 06:04 UTC, ThisaruGuruge commented on task-ballerina/src/task/commons.bal
> +# + noOfRecurrences - Number of times to trigger the task after which the task stops running. If It will be zero,
```suggestion
# + noOfRecurrences - Number of times to trigger the task after which the task stops running. If It is zero,
```

2020-11-06 06:04 UTC, ThisaruGuruge commented on task-native/src/main/java/org/ballerinalang/stdlib/task/utils/TaskConstants.java
> +    TaskConstants() {
shouldn't this be `private`?

2020-11-06 07:11 UTC, MadhukaHarith92 commented on task-ballerina/src/task/commons.bal
> +# + noOfRecurrences - Number of times to trigger the task after which the task stops running. If It will be zero,
```suggestion
# + noOfRecurrences - Number of times to trigger the task after which the task stops running. If It is zero,
```

2020-11-06 07:13 UTC, MadhukaHarith92 commented on task-ballerina/src/task/listener.bal
> +                panic ListenerError("Wrong misfire policy has given for the one-time execution timer tasks.");
```suggestion
                panic ListenerError("Wrong misfire policy has been given for the one-time execution timer tasks.");
```

2020-11-06 07:14 UTC, MadhukaHarith92 commented on task-ballerina/src/task/listener.bal
> +                panic ListenerError("Wrong misfire policy has given for the repeating execution timer tasks.");
```suggestion
                panic ListenerError("Wrong misfire policy has been given for the repeating execution timer tasks.");
```

2020-11-06 07:18 UTC, kalaiyarasiganeshalingam commented
The transaction also worked with this changes.

2020-11-06 07:33 UTC, MadhukaHarith92 commented on task-native/src/main/java/org/ballerinalang/stdlib/task/actions/TaskActions.java
> +    @SuppressWarnings("unchecked")
Shall we put an explanatory comment as to why this unchecked warning is being suppressed?

2020-11-06 07:35 UTC, MadhukaHarith92 commented on task-native/src/main/java/org/ballerinalang/stdlib/task/objects/TaskScheduler.java
> +
```suggestion
```

2020-11-06 07:39 UTC, MadhukaHarith92 commented on task-native/src/main/java/org/ballerinalang/stdlib/task/utils/Utils.java
> +            // Quartz uses number of repeats but total number of runs are counted here.
```suggestion
            // Quartz uses the number of repeats but the total number of runs are counted here.
```

2020-11-06 07:40 UTC, MadhukaHarith92 commented on task-native/src/main/java/org/ballerinalang/stdlib/task/utils/Utils.java
> +            // Hence, 1 is subtracted from the `maxRuns` to get the repeat count.
```suggestion
            // Hence, `maxRuns` is subtracted by 1 to get the repeat count.
```

2020-11-06 10:38 UTC, ThisaruGuruge approved these changes
LGTM

2020-11-06 10:42 UTC, MadhukaHarith92 approved these changes

2020-11-06 11:37 UTC, BuddhiWathsala approved these changes

2020-11-06 11:39 UTC, merged